### ISSUE TITLE
经常会连接失败

### ISSUE THREAD

**Issue by wuyu-zyong** [WhiteMagic2014/tts-edge-java#6]
加入程序以后，运行一两分钟就会出现导致失败。
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by wuyu-zyong** [comment]
主要是卡住了，是不是忘记设置超时了

**Comment by WhiteMagic2014** [comment]
> 主要是卡住了，是不是忘记设置超时了

更新了一个版本 1.2.2 现在可以给 TTS 设置 超时时间，看看能否解决

**Comment by jimisun123** [comment]
> > 主要是卡住了，是不是忘记设置超时了
> 
> 更新了一个版本 1.2.2 现在可以给 TTS 设置 超时时间，看看能否解决

我引入项目所有的网络都无法连接成功，跟上面的提示一样是不是现在edge屏蔽了国内请求了？

**Comment by yzygenuine** [comment]
如何接上代理 呢。是不是本机连接VPN就可以？

**Comment by WhiteMagic2014** [comment]
更新版本1.2.5. 其中有参数 isRateLimited。 如果在国内用不了 设置为true即可

**Comment by WhiteMagic2014** [comment]
> 如何接上代理 呢。是不是本机连接VPN就可以？

更新版本1.2.5. 其中有参数 isRateLimited。 如果在国内用不了 设置为true即可

**Comment by WhiteMagic2014** [comment]
> > > 主要是卡住了，是不是忘记设置超时了
> > 
> > 
> > 更新了一个版本 1.2.2 现在可以给 TTS 设置 超时时间，看看能否解决
> 
> 我引入项目所有的网络都无法连接成功，跟上面的提示一样是不是现在edge屏蔽了国内请求了？

更新版本1.2.5. 其中有参数 isRateLimited。 如果在国内用不了 设置为true即可
